### ISSUE TITLE
Mac或Linux上怎么兼容呢？

### ISSUE THREAD

**Issue by HouWan** [WangXuan95/TinyPNG-kmeans#1]
如题一样，在Mac和Linux无法使用`optipng.exe`文件，有木有兼容方案呢？

**Comment by WangXuan95** [comment]
去 [OptiPNG官网](https://optipng.sourceforge.net/) 上下载源码，然后编译成 Mac/Linux 上的可执行文件。

**Comment by WangXuan95** [comment]
你好，我已经加入了对 linux 的支持，linux 和 windows 上用法一样，用python运行那个python文件即可：

```
python tinypng.py <输入目录名> <输出目录名> <色彩数量>
```
