### ISSUE TITLE
请教一个透明通道问题

### ISSUE THREAD

**Issue by HouWan** [WangXuan95/TinyPNG-kmeans#2]
我试了很多png压缩脚本或者工具，发现压缩之后，png会失去透明通道，可是在特殊情况下，我又需要保留透明通道。请问您有遇到这种问题，或者对透明通道有研究吗？

下面这个图片是在我在Mac系统上，查看一个png图片的详情，能看到包含`Alpha channel`，不过我压缩之后，会变成`NO`
![WX20230412-205525@2x](https://user-images.githubusercontent.com/13991710/231464563-61f9b773-496c-4d3d-8e53-aa6771a7ff3f.png)

**Comment by WangXuan95** [comment]
本库用到了两种压缩原理：色域量化 (原创)、Deflate 极限压缩 (使用的 [OPTPNG](https://optipng.sourceforge.net/) 。其中色域量化的压缩效果显著，而Deflate 极限压缩效果比较小。
如果你要保留 ALPHA 通道，很可惜色域量化就不能用了，因为色域量化依赖于 PNG 的调色板模式，而调色板模式只支持 RGB 而不支持 RGBA 。同理，像 [tinypng](https://tinypng.com/) 这种基于色域量化的压缩似乎也不会保留 ALPHA 通道。
你可以只使用 [OPTPNG](https://optipng.sourceforge.net/) 来压缩，优点是完全无损，不像色域量化有所损失。但压缩率就很有限了。

**Comment by HouWan** [comment]
> 本库用到了两种压缩原理：色域量化 (原创)、Deflate 极限压缩 (使用的 [OPTPNG](https://optipng.sourceforge.net/) 。其中色域量化的压缩效果显著，而Deflate 极限压缩效果比较小。 如果你要保留 ALPHA 通道，很可惜色域量化就不能用了，因为色域量化依赖于 PNG 的调色板模式，而调色板模式只支持 RGB 而不支持 RGBA 。同理，像 [tinypng](https://tinypng.com/) 这种基于色域量化的压缩似乎也不会保留 ALPHA 通道。 你可以只使用 [OPTPNG](https://optipng.sourceforge.net/) 来压缩，优点是完全无损，不像色域量化有所损失。但压缩率就很有限了。

原来如此，学到了，使用`tinypng`的确也会失去透明通道，而且发现，要保留透明通道，压缩效果很差。
从这个角度来看，`webp`格式，不失为一种替代品。
